# Generated by Django 5.1.15 on 2026-07-09 20:58

import django.db.models.deletion
import game.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models._make_game_code, help_text='Join code students type to enter the game.', max_length=8, unique=True)),
                ('name', models.CharField(default='SEM Trading Floor', max_length=120)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('running', 'Running'), ('finished', 'Finished')], default='setup', max_length=10)),
                ('num_rounds', models.PositiveIntegerField(default=5)),
                ('starting_budget', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('min_bid', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=8)),
                ('ad_slots', models.PositiveIntegerField(default=3, help_text='Ad positions available per keyword.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Round order for this keyword.')),
                ('label', models.CharField(max_length=120)),
                ('asset_class', models.CharField(blank=True, help_text='Flavor text, e.g. "Branded blue chip" or "Speculative meme".', max_length=80)),
                ('search_volume', models.PositiveIntegerField(default=5000, help_text='Impressions available per shown ad.')),
                ('ctr_curve', models.JSONField(blank=True, default=list, help_text='Click-through rate by position; empty = use default curve.')),
                ('conversion_rate', models.FloatField(default=0.03, help_text='Share of clicks that convert (0-1).')),
                ('order_value', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Revenue per conversion.', max_digits=10)),
                ('reserve_price', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Floor CPC paid by the lowest shown ad.', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='game.game')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('revealed', 'Revealed')], default='pending', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.game')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='game.keyword')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('game', 'number')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.round'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('effect', models.JSONField(blank=True, default=dict, help_text='e.g. {"keyword": "dubai", "search_volume_mult": 1.6}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.game')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='game.round')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('budget_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cumulative_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cumulative_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cumulative_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_bot', models.BooleanField(default=False)),
                ('bot_aggressiveness', models.FloatField(default=1.0, help_text="Bid multiplier vs. a keyword's fair value (bots only).")),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='game.game')),
            ],
            options={
                'ordering': ['-cumulative_profit', 'name'],
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_rank', models.FloatField(default=0.0)),
                ('position', models.PositiveIntegerField(blank=True, help_text='Null = ad not shown.', null=True)),
                ('actual_cpc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('conversions', models.FloatField(default=0.0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('roas', models.FloatField(blank=True, help_text='revenue / spend; null if no spend.', null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('round', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('ad_text', models.CharField(blank=True, max_length=200)),
                ('landing_choice', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='game.team')),
            ],
            options={
                'unique_together': {('round', 'team')},
            },
        ),
    ]
