# Generated by Django 5.1.15 on 2026-07-09 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='session_key',
        ),
        migrations.AddField(
            model_name='game',
            name='max_team_size',
            field=models.PositiveIntegerField(default=4, help_text='Maximum members per team. Set to 1 to force solo play.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.team')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('game', 'session_key')},
            },
        ),
    ]
