# Generated by Django 5.1.15 on 2026-07-21 23:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_round_result_bid_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='min_bid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lowest bid students may enter; 0 lets any non-negative bid through (keyword reserve prices still act as the auction floor).', max_digits=8),
        ),
    ]
