# Generated by Django 5.1.15 on 2026-07-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_min_bid_zero_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_mode',
            field=models.CharField(choices=[('team', 'Team Mode'), ('individual', 'Individual Mode')], default='team', max_length=12),
        ),
        migrations.AddField(
            model_name='game',
            name='quality_apply_bots',
            field=models.BooleanField(default=False, help_text='Apply the quality score settings to bots too.'),
        ),
        migrations.AddField(
            model_name='game',
            name='quality_max',
            field=models.FloatField(default=10.0, help_text='Random mode: upper bound.'),
        ),
        migrations.AddField(
            model_name='game',
            name='quality_min',
            field=models.FloatField(default=0.0, help_text='Random mode: lower bound.'),
        ),
        migrations.AddField(
            model_name='game',
            name='quality_mode',
            field=models.CharField(choices=[('uniform', 'Uniform Player Quality Score(s)'), ('random', 'Randomize Player Quality Score(s)'), ('manual', 'Manually Set Player Quality Score(s)')], default='uniform', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='quality_show_players',
            field=models.BooleanField(default=True, help_text='Show players their per-keyword quality scores.'),
        ),
        migrations.AddField(
            model_name='game',
            name='quality_uniform',
            field=models.FloatField(default=5.0, help_text='Quality for every player in Uniform mode.'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive keywords stay in the list but are left out of the round schedule.'),
        ),
        migrations.AddField(
            model_name='team',
            name='quality_max',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='team',
            name='quality_min',
            field=models.FloatField(default=0.0),
        ),
    ]
