# Generated by Django 5.1.15 on 2026-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_play_mode_quality_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='timer_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Countdown length once a round opens.'),
        ),
    ]
